language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4

env:
- WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 7.4
    env: WP_VERSION=latest WP_MULTISITE=1 COVERAGE=1
  - php: 7.4
    env: LINT=1

before_install:
- |
  if [[ "$LINT" == "1" ]]; then
    export PHPCS_DIR=/tmp/phpcs
    export LINTS_DIR=/tmp/lint
    git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
    git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $LINTS_DIR
    $PHPCS_DIR/bin/phpcs --config-set installed_paths $LINTS_DIR
    phpenv rehash
  fi;

before_script:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini; fi
- if find . -name "*.php" -exec php -l {} \; | grep "unexpected $end"; then exit 1; fi
- composer install --prefer-source --optimize-autoloader --no-scripts
- bash bin/install-wp-tests.sh gravitypdf_test root '' localhost $WP_VERSION

script:
- |
  if [[ "$LINT" == "1" ]]; then
    $PHPCS_DIR/bin/phpcs -p .
  elif [[ "$COVERAGE" == "1" ]]; then
   yarn run test:coverage
   ./vendor/bin/phpunit --coverage-clover=tmp/coverage/report-xml/php-coverage.xml -c phpunit.xml
  else
   ./vendor/bin/phpunit -c phpunit.xml
  fi

after_success:
- if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash); fi